let productos = [
    {
        id: 1,
        name: "Windsor",
        type: "hibrida",
        size: "145",
        price: 150000,
        stock: 5,
    },
    {
        id: 2,
        name: "Windsor",
        type: "hibrida",
        size: "149",
        price: 150000,
        stock: 7,
    },
    {
        id: 3,
        name: "Windsor",
        type: "hibrida",
        size: "153",
        price: 150000,
        stock: 3,
    },
    {
        id: 4,
        name: "Salmon",
        type: "park",
        size: "145",
        price: 120000,
        stock: 6,
    },
    {
        id: 5,
        name: "Salmon",
        type: "park",
        size: "149",
        price: 120000,
        stock: 2,
    },
    {
        id: 6,
        name: "Salmon",
        type: "park",
        size: "153",
        price: 120000,
        stock: 3,
    },
    {
        id: 7,
        name: "Terrain",
        type: "wind",
        size: "145",
        price: 140000,
        stock: 10,
    },
    {
        id: 8,
        name: "Terrain",
        type: "wind",
        size: "149",
        price: 140000,
        stock: 1,
    },
    {
        id: 9,
        name: "Terrain",
        type: "wind",
        size: "153",
        price: 140000,
        stock: 7,
    },
    {
        id: 10,
        name: "Contrast",
        type: "lancha",
        size: "145",
        price: 130000,
        stock: 4,
    },
    {
        id: 11,
        name: "Contrast",
        type: "lancha",
        size: "149",
        price: 130000,
        stock: 8,
    },
    {
        id: 12,
        name: "Contrast",
        type: "lancha",
        size: "153",
        price: 130000,
        stock: 3,
    }
]